language: android

jdk:
    - oraclejdk8

env:
    matrix:
        - ANDROID_TARGET=android-24  ANDROID_ABI=x86

android:
    components:
        - platform-tools
        - tools
        - build-tools-24.0.2
        - $ANDROID_TARGET
        - sys-img-x86-$ANDROID_TARGET
        - extra-android-m2repository
        - extra-google-m2repository

script:
    ./gradlew build

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/